background = #0D0010
foreground = #FFD6EC

palette = 0=#0D0010
palette = 1=#FF0066
palette = 2=#FF66B3
palette = 3=#FF80C0
palette = 4=#CC0066
palette = 5=#FF00AA
palette = 6=#FF99D6
palette = 7=#FFCCEE

palette = 8=#3D0022
palette = 9=#FF1493
palette = 10=#FFAAD5
palette = 11=#FF80B3
palette = 12=#FF4DCC
palette = 13=#FF33BB
palette = 14=#FFB3D9
palette = 15=#FFE6F2
